### ISSUE TITLE
Sort navigation by number of responses?

### ISSUE THREAD

**Issue by dmartines** [RagtagOpen/marchon-data-viz#10]
Today we sort slider navigation alphabetically ... but some of the key issues take a while to appear.  May I suggest we sort by number of responses?  See example in this sheet:

[https://docs.google.com/spreadsheets/d/1SnWINjSFPa2BCnXaTb39tNjeErvrvQfDYofDbOO5hl0/edit?usp=sharing](url)

**Comment by jillh510** [comment]
I expect it'll wind up sorted by whatever order March On puts the issues in, in their declaration.
