### ISSUE TITLE
Arrows get cut off on mobile

### ISSUE THREAD

**Issue by jillh510** [RagtagOpen/marchon-data-viz#12]
The arrows to the left and right of the header get cut off at mobile screen resolution.

**Comment by jillh510** [comment]
Admittedly this is a narrow browser window on a laptop, not an actual phone.
![screen shot 2018-06-22 at 1 58 21 pm](https://user-images.githubusercontent.com/2319837/41798949-706f4df8-7624-11e8-90b8-af4792d43ef1.png)

**Comment by dryan** [comment]
Fixed in rebuild.html

**Comment by dmartines** [comment]
Should we close this issue?  Is it still happening on mobile?  (remember - testing on narrow browser window is not the same as mobile since viewports are different)
